apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flask-demo-app
  name: flask-demo-app
spec:
  containers:
  - image: poroko/flask-demo-app
    name: mypython
    ports:
    - containerPort: 8081
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
